---
# Start Cloud Init Scripts
- name: Cloud Init Scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/cloud/scripts/custom-per-boot/{{ item | basename }}"
    mode: "0755"
    owner: root
    group: root
  with_fileglob:
    - ../files/var/lib/cloud/scripts/custom-per-boot/*.sh
# End Cloud Init Scripts

# Start Install
- name: INSTALL OVN
  ansible.builtin.package:
    name:
      - ovn-central
    state: present

- name: DISABLE OVN services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - ovn-central.service
    - ovn-northd.service
    - ovn-ovsdb-server-nb.service
    - ovn-ovsdb-server-sb.service

- name: Remove OVN storage dir
  ansible.builtin.file:
    path: /var/lib/ovn
    state: absent

- name: Create OVN storage dir
  ansible.builtin.file:
    path: /var/lib/ovn
    owner: root
    group: root
    mode: '0755'
    state: directory
# End Install

- name: OVSDB Service Consul Config
  ansible.builtin.template:
    src: etc/consul.d/50_ovn-ovsdb.hcl
    dest: /etc/consul.d/50_ovn-ovsdb.hcl
    mode: "0644"
    owner: consul
    group: consul

- name: Place ovn-ovsdb-connection service
  ansible.builtin.template:
    src: etc/systemd/system/ovn-ovsdb-connection.service
    dest: /etc/systemd/system/ovn-ovsdb-connection.service
    mode: "0644"

- name: Place ovn-ovsdb-connection timer
  ansible.builtin.template:
    src: etc/systemd/system/ovn-ovsdb-connection.timer
    dest: /etc/systemd/system/ovn-ovsdb-connection.timer
    mode: "0644"

- name: SystemD daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable ovn-ovsdb-connection timer
  ansible.builtin.systemd:
    name: ovn-ovsdb-connection.timer
    enabled: true
