## {{ ansible_managed }}

scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ["prometheus"]
    scheme: https
    static_configs:
      - targets: ["hashi-vault-1.us-homelab1.hl.rmb938.me:8200"]
      - targets: ["hashi-vault-2.us-homelab1.hl.rmb938.me:8200"]
      - targets: ["hashi-vault-3.us-homelab1.hl.rmb938.me:8200"]
