---
# Start Install
- name: UBUNTU CLOUD KEYRING
  ansible.builtin.package:
    name: ubuntu-cloud-keyring
    state: present

- name: INSTALL OPENSTACK REPO
  ansible.builtin.apt_repository:
    repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu noble-updates/dalmatian main

- name: INSTALL OPENSTACK CLIENT Ubuntu
  ansible.builtin.package:
    name:
      - python3-openstackclient
      - python3-osc-placement
      - python3-octaviaclient

- name: INSTALL SUPPORTING LIBS
  ansible.builtin.package:
    name:
      - python3-psycopg
      - python3-consul

- name: INSTALL NOVA
  ansible.builtin.package:
    name:
      - nova-api
      - nova-conductor
      - nova-scheduler
      - nova-novncproxy
    state: present

- name: GET PACKAGE FACTS
  ansible.builtin.package_facts:
    manager: "auto"

- name: DISABLE Nova Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
# End Install

- name: Own nova dir
  ansible.builtin.file:
    path: /etc/nova
    owner: nova
    group: nova
    mode: "0750"
    state: directory
    recurse: true
